name: Check Code Quality and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-eslint:
    name: Lint ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=18.x"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  lint-prettier:
    name: Lint Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=18.x"

      - name: Run Prettier
        run: npx prettier . --check

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs:
      - lint-eslint
      - lint-prettier

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ">=18.x"

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
