name: Check Deploy Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Test Build Next.js Project
        run: npm run build
